### ISSUE TITLE
[Action Button] Active state different between "standard" and "emphasized" variants

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1139] opened 2021-02-25 15:51 UTC
## Description
The "emphasized" variant seems to override the "active" state that comes with the "standard" variant.

## Steps to reproduce
1. Go to https://opensource.adobe.com/spectrum-css/actionbutton.html
2. `pointerdown` on any of the "standard" variant action buttons
3. Observe the explicit "neutral", "hover", and "active" states on the button.
4. `pointerdown` on any of the "emphasized - default" variant action buttons
5. Observe the explicit "neutral" and "hover" states but the lack of an "active" state.

## Expected behavior
It seems like the "active" state should be the same between the two variant combinations, but it's possible that a "emphasized - default - active" variant is intended?

## Environment
 - **Spectrum CSS version:** latest
 - **Browser(s) and OS(s):** Chrome 88.0.4324.192

CC: @spdev3000

**Comment by lazd** [comment] 2021-11-17 19:42
Looks like a duplicate of #877

**Closed** 2021-11-17 19:50 UTC
Labels: bug
