### ISSUE TITLE
No emphasized radio button state

### ISSUE THREAD

**Issue by JacobDFrank** [adobe/spectrum-css#430] opened 2019-12-09 23:13 UTC
## Description

An emphasized version of the radio button doesn't exist in the CSS implementation but it is in the regular documentation.

## Steps to reproduce

1. An emphasized radio button exists https://spectrum.corp.adobe.com/page/radio-button/#Emphasis
2. But, an emphasized radio button in the CSS implementation doesn't exist.

## Expected behavior

I would expect a `is-emphasized` class that makes the radio button blue upon being selected.

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by lazd** [comment] 2019-12-10 01:07
Duplicate of https://github.com/adobe/spectrum-css/issues/349, also this technically should be a feature request since it's adding something new, not a bug.

**Closed by lazd** 2019-12-10 01:07 UTC
Labels: bug
