### ISSUE TITLE
Menu items incorrectly overflow on IE11

### ISSUE THREAD

**Issue by iost** [adobe/spectrum-css#216] opened 2019-07-10 15:16 UTC
Problem:Country dropdown on sign up is opening from middle of the list and list is going out of the box

Method:
1.Launch LBS
2.Click signup on welcome screen
3. Click on country dropdown

Result: Country dropdown on sign up is opening from middle of the list and list is going out of the box

<img width="335" alt="country_dropdown" src="https://user-images.githubusercontent.com/10536129/60981310-c2063f80-a33e-11e9-81a1-45081cd8521c.png">
<img width="336" alt="country_dropdown2" src="https://user-images.githubusercontent.com/10536129/60981311-c29ed600-a33e-11e9-95a0-2369fe9ed115.png">

Expected: Dropdown should open from starting and within the box

**Comment by lazd** [comment] 2019-07-10 18:21
Is this using React Spectrum? Spectrum CSS itself doesn't manage the positioning of a Dropdown's Popover, so this shouldn't be a Spectrum CSS bug.

**Comment by nordanga** [comment] 2019-07-11 11:26
@lazd It's using react-spectrum, but this bug isn't about the positioning of the popover. The issue is that the list is overflowing on IE11. As you can see on the screenshot, the list doesn't stay within its container, but rather just continue out of its borders.

**Comment by iost** [comment] 2019-07-15 11:59
@lazd Could you give us an update on this one?

**Comment by lazd** [comment] 2019-07-22 06:42
Hmm, can you create a codepen that reproduces this issue without React Spectrum, or a code sample to reproduce it with React Spectrum? I need something to play with to start debugging this issue.

**Comment by nordanga** [comment] 2019-07-23 13:40
This is from your storybook on IE11 (virtual machine), and all I did was add a `max-height: 300px;` to the `.spectrum-Popover` element (which is what react-spectrum, presumably, is doing when the dropdown is about to overflow out of the viewport), and added the additional elements needed.

![image](https://user-images.githubusercontent.com/52739781/61716770-7b660b80-ad68-11e9-94f8-7b6bd432258f.png)

**Comment by lazd** [comment] 2019-07-23 18:56
@nordanga thanks, that's what I needed.

Looks like it's a known flex-bug, and there are a couple ways to fix it: https://github.com/philipwalton/flexbugs/issues/216

Seems like using `height` instead of `max-height` is the easiest fix, or you can wrap the element is another flex box. Go ahead and implement one of these temporary fixes, keep this issue open, and we can look into adding a wrapping flex box in a future version.

**Comment by nordanga** [comment] 2019-10-01 07:33
@lazd Using `height` will also have the side-effect of the white container being the entire size that is given, if the list is small we'll have only a few items in a large box instead. Max-height is also being controlled through javascript by the react-spectrum component which is using it, something we can't control.

The item cannot be wrapped as it is injected and removed by react-spectrum into the body element of the page, used globally.

**Comment by lazd** [comment] 2019-10-01 15:36
@nordanga understood. The patch for this will involve adding a wrapper, we can update the markup examples here and submit a PR to React Spectrum. I'll see if PM will prioritize this for an upcoming sprint.

**Comment by oppy27** [comment] 2019-10-08 09:18
Any update?

**Comment by lazd** [comment] 2019-10-28 19:26
So it turns out this can be fixed by adding `overflow-y: auto` to the Popover. We cannot make this change in Spectrum CSS, however, as it breaks the positioning of the Popover's tip when used in other contexts.

It also turns out this happens for Select, Combobox, Autocomplete, and Dropdown button -- basically anything that shows a list of Menu items inside of a Popover

To address this, I've created a PR against React Spectrum: https://github.com/adobe/react-spectrum/pull/665 This will hopefully be reviewed and merged quickly as it's a very simple fix, with the subsequent release happening in a couple of weeks.

I'll close this issue now as the fix for it cannot happen in Spectrum CSS.

**Closed by lazd** 2019-10-28 19:26 UTC
Labels: Component: Dropdown, IE Bug, browser rendering bug
