### ISSUE TITLE
Slider track missing

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#504] opened 2020-01-27 10:17 UTC
## Description
In the docs, the Slider track on the first examples is not visible

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/slider/#Standard

## Additional context
The problem is the width of the two tracks is not specified.

Specified markup:
````
<div class="spectrum-Slider-controls">
    <div class="spectrum-Slider-track"/>
    <div class="spectrum-Slider-handle" style="left: 40%;">
      <input type="range" class="spectrum-Slider-input" value="14" step="2" min="10" max="20">
    </div>
    <div class="spectrum-Slider-track"/>
  </div>
````
It should be:
````
<div class="spectrum-Slider-controls">
    <div class="spectrum-Slider-track" style="width: 40%;"/>
    <div class="spectrum-Slider-handle" style="left: 40%;">
      <input type="range" class="spectrum-Slider-input" value="14" step="2" min="10" max="20">
    </div>
    <div class="spectrum-Slider-track" style="width: 60%;"/>
  </div>
````

**Comment by lazd** [comment] 2020-01-27 21:26
Duplicate of #397

**Closed by lazd** 2020-01-27 21:26 UTC
Labels: documentation

**Comment by Harbs** [comment] 2020-01-27 21:36
Sorry. I should have searched issues first...

**Comment by lazd** [comment] 2020-01-28 03:38
@Harbs not a problem! We'd rather have a duplicate report than no report at all. Keep 'em coming!
