### ISSUE TITLE
[Button] Icon after label removed?

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1086] opened 2020-12-08 04:20 UTC
## Description
The code found here https://unpkg.com/browse/@spectrum-css/button@3.0.0-beta.5/dist/index-vars.css#L142 in the `beta.5` release of the `Button` pattern persisted the ability to have an `Icon` after the `label` element in the button, but it seems to be removed in the most recent beta. Was this removal intentional, or will we see that returned in future releases? There's a little but of wonkiness in `beta.6` where the selectors are duplicated in a way that doesn't seem required that makes me think this was maybe an oversight in the large amount of changes therein: https://unpkg.com/browse/@spectrum-css/button@3.0.0-beta.6/dist/index-vars.css#L357

## Expected behavior
Styles for icon after label are available.

## Environment
 - **Spectrum CSS version:** @spectrum-css/button@3.0.0-beta.5 -> beta.6
 - **Browser(s) and OS(s):** All

**Comment by lazd** [comment] 2020-12-08 19:08
Yeah, it was removed, icon must come first. This is because t-shirt sizing changes lots of paddings as things get bigger, and to make it look right for the design, we had to make some assumptions about the order of the elements. [The comments in the source file explain the logic](https://github.com/adobe/spectrum-css/blob/main/components/button/index.css#L83-L111). If there's a way to do this without having to force ordering of icon + label, I'm down!

**Comment by Westbrook** [comment] 2020-12-08 19:12
Is there something I'm missing that prevents use of:
```
  .spectrum-Button-label + .spectrum-Icon {
    /* Have gap on on the left */
    padding-inline-start: var(--spectrum-button-primary-icon-gap);

    /*
      Have no padding on the right (it's built into the element)
      This will fail if --spectrum-button-primary-textonly-padding-right !== --spectrum-button-padding-right
    */
    padding-inline-end: 0;
  }
```
Similarly, how much longer until we can leverage `gap`? 😞 Seems like a while: https://caniuse.com/?search=gap unless we use `display: grid` over `flex` here...

**Comment by lazd** [comment] 2020-12-09 16:36
Ah I see, you're right, there's no reason why we can't support right-side icons based on markup order if we do something like that.

You're saying you want this, but not ugly, right?
![image](https://user-images.githubusercontent.com/201344/101658187-9d157080-39f9-11eb-9929-40f117ba9f4c.png)

What the use case? I wonder if this would anger the design gods...

**Comment by Westbrook** [comment] 2020-12-09 16:40
This is what we had _before_:

![image](https://user-images.githubusercontent.com/1156657/101658415-ffc73600-3a12-11eb-9ed4-dbc56f4ac9ea.png)

I can't say that I know where it came from, just that is as part of our library (and the Spectrum CSS output we built from). Beyond that I don't specifically have a use case that I know of...which is why it could be just a _deprecation_ and I'd be OK with it.

The above CSS structure is roughly what we had been consuming before, if we wanted to continue to deliver it to end users.

**Comment by snowystinger** [comment] 2020-12-09 18:06
So we've actually solved this like so: https://github.com/adobe/react-spectrum/blob/main/packages/%40adobe/spectrum-css-temp/components/button/index.css#L164

**Comment by GarthDB** [comment] 2021-01-14 18:17
@Westbrook @snowystinger I'm confident we can add this functionality back (being able to order the 2 elements either way), but I wasn't sure it's something the design guidelines allows. I brought this up with the design team and they asked for some use cases. Do you have any you can post?

**Comment by snowystinger** [comment] 2021-01-14 18:24
When we talked to design about it, they were clear that it should only have one visual ordering [Icon, Text], the other was invalid. I'm unaware of any use cases where it should be the other way around and no one has brought it up in the slack channel or issues.

**Comment by GarthDB** [comment] 2021-01-14 18:27
@snowystinger so when you said above you solved it and they are visually the same, does that mean that regardless of the dom order, it always shows the icon on left and label on right? or it allows the undocumented reversed order?

**Comment by Westbrook** [comment] 2021-01-14 18:29
I'm also unsure/unaware of any usage. As noted above, I only noticed this change in that I was supporting the previously offered capabilities of Spectrum CSS.

**Comment by GarthDB** [comment] 2021-01-14 18:32
So we could force the order so it doesn't enable the reverse order, but it also doesn't exactly break people using it in an unsupported way. Would that help @Westbrook?

**Comment by Westbrook** [comment] 2021-01-14 18:35
If the intent is to deprecate the usage of buttons with icons on the right, it would be no issue for us functionally. I'm only looking to confirm that's the intent and this wasn't a regression.

**Comment by GarthDB** [comment] 2021-01-14 18:37
@Westbrook ok. I am closing it. My assumption, from speaking with the design team, is that it wasn't intentionally enabled (or shouldn't have been enabled) in the first place so it's not a regression it's just breaking an unsupported use case.

**Closed by GarthDB** 2021-01-14 18:37 UTC
Labels: bug

**Comment by snowystinger** [comment] 2021-01-14 21:19
@GarthDB correct, no matter what order they are in the DOM, they will always render visually in the correct order
