### ISSUE TITLE
Dilato: IE only: Core: There are two loading icons when clicking on 'Continue' button in SUSI page

### ISSUE THREAD

**Issue by iost** [adobe/spectrum-css#226] opened 2019-07-25 15:52 UTC
Problem:
There are two loading icons when clicking on 'Continue' button in SUSI page
Steps:
1. Launch https://graduation.stage.adobe.com/
2. Click Getting Started button
3. Click Continue button
4. Input a T2 or T3 account
5. Then click on 'Continue' button and observe
Actual result:
There are two loading icons when clicking on 'Continue' button in SUSI page
Expected result:
There displayed one loading icon when clicking on 'Continue' button in SUSI page
![Two loading icons displayed](https://user-images.githubusercontent.com/10536129/61888955-3af3c280-af0d-11e9-9017-7b051fe1b528.png)

**Comment by lazd** [comment] 2019-07-25 16:00
@iost, thanks for the report. Unfortunately, I cannot access the link you've provided (Access denied), and I don't have any T2/T3 account logins.

Can you please indicate the exact markup you're using here and the version of Spectrum CSS that's running? Or even better, create a codepen based on this template that reproduces the issue: https://codepen.io/pen?template=zMyYEO

I tried to reproduce this issue on our docs at http://opensource.adobe.com/spectrum-css/2.13.0/docs/#circle-loader---indeterminate, but it works fine in IE 11.

If you can screen grab a video and let me know what markup/Spectrum CSS versioned is being used, that would be very helpful.

**Comment by GarthDB** [comment] 2020-09-09 20:23
Closing this since we couldn't reproduce and are dropping support for IE11.

**Closed by GarthDB** 2020-09-09 20:23 UTC
Labels: Component: Progress Circle
