### ISSUE TITLE
Add updated sizing to Avatar

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#697] opened 2020-04-20 22:56 UTC
## Description
Sizing and designs can be found [here](https://spectrum-contributions.corp.adobe.com/page/avatar-beta/#Size).

**Comment by Westbrook** [comment] 2020-12-03 17:35
Now that this sizing is "officially" in Spectrum, where does this fall as far as priority for implementing at the Spectrum CSS level?

**Comment by lazd** [comment] 2020-12-06 19:05
Looks like a dupe of #368

**Comment by lazd** [comment] 2020-12-06 19:06
Looking at DNA, we have different sizes for Avatar, but they're numerical, not t-shirt sized... That's weird AF.

@NateBaldwinDesign not sure if we discussed this already, but are Avatars going to stay with numerical sizing, or are we going to use S/M/L etc.

**Comment by pfulton** [comment] 2022-07-11 17:29
We'll take a new look at this one during our migration to core tokens.

**Closed by pfulton** 2022-07-11 17:29 UTC
Labels: Component: Avatar, beta design
