### ISSUE TITLE
Should ActionBar sticky/fixed be named something else?

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#163] opened 2019-05-14 17:36 UTC
Currently, ActionBar has a `--sticky` modifier to indicate that it stays the same place within the table as it scrolls, and a `--fixed` modifier that indicates it will stay the same place on the page. These are very much CSS-influenced names that are unintuitive to the unenlightened, should we name them something more descriptive?

synced to jira: https://jira.corp.adobe.com/browse/CSS-140

**Comment by GarthDB** [comment] 2020-02-25 18:15
[ ] Check in with content strategy

**Comment by misterbrownlee** [comment] 2020-08-24 17:40
Was `blocked by design`

**Comment by misterbrownlee** [comment] 2022-05-17 18:51
retrying jira sync 🙄

**Comment by misterbrownlee** [comment] 2022-07-18 17:27
Closing this, it's tracked in Jira

**Closed by misterbrownlee** 2022-07-18 17:27 UTC
Labels: question, breaking change, blocked, sync to jira, ask design
